### ISSUE TITLE
Reg: Video call is not working when we use different Network Connections

### ISSUE THREAD

**Issue by Kishore1224** [DangLienMinh/webrtc_client#4]
Hi

Thanks for your Effort..
Am facing issue with Video Call while the Android devices are different Networks..
Within the network its working fine.. if it is in different Networks.. It not..
Can anyone Suggest the way to overcome this..

Thanks

**Comment by minhdl93** [comment]
Dear Kishore1224,

When I was doing this project, I could only implement it in my local network, I have also try to find a way to call from different networks but it did not work.

So if you o anybody could figure a way, it would be perfect,

**Comment by Longstreet** [comment]
That is because you need to have a STUN/TURN server to bypass NAT. You can run the STUN/TURN server on the same server you're running your signalling on. You can also use public STUN servers (google for a free list) and use those to test out stuff if you wanted.

In WebRTCClient.java, in the public WebRTC (Listener) class, you can type in the following:

        iceServers.add(new PeerConnection.IceServer("stun:IP_ADDRESS"));

For TURN you add the following line:

        iceServers.add(new PeerConnection.IceServer("turn:TURN_ADDRESS","username","password"));

Note that WebRTC will usually try to connect to STUN first and then if that doesn't work it will try to log in through TURN. You don't need a TURN server to make a connection (just have to keep trying till it works, or try different internet connections as yours might be too secure to allow STUN reliably). TURN is mostly a relay for when STUN doesn't work, but 90% of WebRTC connections go through STUN and is quite reliable. You can add multiple STUN servers with that line and it'll add them to a list and it will go through them one by one till it establishes a connection.

Hope that helps!
